services:
  - type: web
    name: discord-restore-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: DB_PATH
        value: members.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
